# Theme
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

# Site settings
title: Subtitle Edit
tagline: A free and open source subtitle editor
description: Subtitle Edit is a powerful tool for creating, editing, and synchronizing subtitles across multiple platforms.

# UI settings
show_downloads: true

# GitHub Pages defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"